"""lesson xp required

Revision ID: 44bac1551c2d
Revises: 44dfbb0f6140
Create Date: 2025-04-13 17:57:33.482620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bac1551c2d'
down_revision: Union[str, None] = '44dfbb0f6140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('required_experience', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'required_experience')
    # ### end Alembic commands ###
