"""empty message

Revision ID: 4acf53bd1ba9
Revises: c4e77d652be5
Create Date: 2025-04-02 23:20:19.006904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acf53bd1ba9'
down_revision: Union[str, None] = 'c4e77d652be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('lesson', sa.Column('teacher_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'teacher_id')
    op.drop_column('lesson', 'xp')
    # ### end Alembic commands ###
