"""profile_picture_link

Revision ID: a449fe0f14e8
Revises: a69a17b2bd19
Create Date: 2025-06-10 21:54:43.468823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a449fe0f14e8'
down_revision: Union[str, None] = 'a69a17b2bd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture_s3_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture_s3_link')
    # ### end Alembic commands ###
