"""empty message

Revision ID: c4e77d652be5
Revises: ccfd80641e71
Create Date: 2025-04-02 23:16:45.181564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e77d652be5'
down_revision: Union[str, None] = 'ccfd80641e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language_level', sa.String(), nullable=True))
    op.add_column('user', sa.Column('experience', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'experience')
    op.drop_column('user', 'language_level')
    # ### end Alembic commands ###
